AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Environment:
      Variables:
        APP_ENV: prod
        APP_RUNTIME: Runtime\Bref\Runtime
        BREF_LOOP_MAX: 100
        AUTH0_CLIENT_ID: bref-ssm:/app/AUTH0_CLIENT_ID
        AUTH0_CLIENT_SECRET: bref-ssm:/app/AUTH0_CLIENT_SECRET
        MAILER_DSN: bref-ssm:/app/MAILER_DSN
        AUTH0_REDIRECT_URI: https://twjqadat3h.execute-api.ap-southeast-2.amazonaws.com/admin/auth0/callback

Resources:
  Website:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 'Symfony-Serverless'
      CodeUri: .
      Handler: public/index.php
      Timeout: 30 # in seconds (API Gateway has a timeout of 30 seconds)
      MemorySize: 512
      Runtime: provided.al2
      Layers:
        - !Sub 'arn:aws:lambda:${AWS::Region}:534081306603:layer:php-82-fpm:33'
      Events:
        HttpRoot:
          Type: HttpApi
      Policies:
        - Statement:
          - Sid: SSMGetParameterPolicy
            Effect: Allow
            Action:
              - 'ssm:GetParameters'
              - 'ssm:GetParameter'
            Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/app/*'

Outputs:
  BowlingCokeMoneyWebsiteUrl:
    Description: 'URL of our function in the *Prod* environment'
    Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/'