AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  CustomDomainName:
    Type: String
    Description: The custom domain name for the API
    Default: bowlingcokemoney.com
  HostedZoneId:
    Type: String
    Description: Route53 HostedZone ID for custom domain
    Default: Z02043462K7X1948WL5PW

Globals:
  Function:
    Environment:
      Variables:
        APP_ENV: prod
        APP_RUNTIME: Runtime\Bref\Runtime
        AUTH0_CLIENT_ID: bref-ssm:/app/AUTH0_CLIENT_ID
        AUTH0_CLIENT_SECRET: bref-ssm:/app/AUTH0_CLIENT_SECRET
        AUTH0_REDIRECT_URI: https://bowlingcokemoney.com/admin/auth0/callback
        BREF_LOOP_MAX: 10
        BUGSNAG_API_KEY: bref-ssm:/app/BUGSNAG_API_KEY
        DATABASE_URL: bref-ssm:/app/DATABASE_URL
        MAILER_DSN: bref-ssm:/app/MAILER_DSN

Resources:
  GenerateCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref CustomDomainName
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref CustomDomainName
          HostedZoneId: !Ref HostedZoneId

  # ------ API ------
  HttpApiGateway:
    Type: AWS::Serverless::HttpApi
    Properties:
      Domain:
        DomainName: !Ref CustomDomainName
        CertificateArn: !Ref GenerateCertificate
        Route53:
          HostedZoneId: !Ref HostedZoneId

  # ------ Lambda ------
  Website:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-Website'
      Description: !Sub 'Public website for ${AWS::StackName}'
      CodeUri: .
      Handler: public/index_lambda.php
      Timeout: 30 # in seconds (API Gateway has a timeout of 30 seconds)
      MemorySize: 512
      Runtime: provided.al2
      Layers:
        - !Sub 'arn:aws:lambda:${AWS::Region}:534081306603:layer:php-82:33'
      Events:
        HttpRoot:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApiGateway
      Policies:
        - Statement:
          - Sid: SSMGetParameterPolicy
            Effect: Allow
            Action:
              - 'ssm:GetParameters'
              - 'ssm:GetParameter'
            Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/app/*'

Outputs:
  BowlingCokeMoneyWebsiteUrl:
    Description: 'URL of our function'
    Value: 'https://bowlingcokemoney.com/'