name: Deploy to AWS
on:
    push:
        branches:
            - main
            - feature/bref-runtime

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.2'
                    coverage: none

            -   name: Install dependencies
                uses: ramsey/composer-install@v2
                with:
                    composer-options: '--no-interaction --no-progress --no-dev --no-suggest --no-scripts'

            -   name: Warmup Symfony cache
                run: php bin/console cache:warmup -e prod

            -   name: Install assets
                run: php bin/console assets:install -e prod

            -   name: Build assets
                run: |
                    yarn install
                    yarn build

            -   name: Configure AWS credentials
                uses: aws-actions/configure-aws-credentials@v2
                with:
                    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
                    aws-region: 'ap-southeast-2'

            -   name: Copy assets to s3
                run: |
                    aws s3 sync ./public/build s3://static-assets.bowlingcokemoney.com/public/build --delete
                    aws s3 sync ./public/bundles s3://static-assets.bowlingcokemoney.com/public/bundles --delete

            -   name: Clean up files
                run: |
                    # Move ./public/build/entrypoints.json as Symfony needs it
                    mv ./public/build/entrypoints.json ./entrypoints.json;
                    mv ./public/build/manifest.json ./manifest.json;
                    
                    # Remove not needed files to save space in lambda function
                    rm -rf \
                        ./node_modules \
                        ./public/build \
                        ./public/bundles \
                        ./public/index.php \
                        ./docker-compose.yml \
                        ./package.json \
                        ./webpack.config.js \
                        ./yarn.lock;
                    
                    # Move entrypoints.json back as Symfony needs it
                    mkdir -p ./public/build;
                    mv ./entrypoints.json ./public/build/entrypoints.json;
                    mv ./manifest.json ./public/build/manifest.json;

            -   name: Deploy
                run: |
                    sam deploy \
                        --no-confirm-changeset \
                        --stack-name BowlingCokeMoney \
                        --resolve-s3 \
                        --capabilities CAPABILITY_IAM \
                        --region ap-southeast-2