name: Deploy to AWS
on:
    push:
        branches:
            - main
            - feature/bref-runtime

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.2'
                    coverage: none

            -   name: Install dependencies
                uses: ramsey/composer-install@v2
                with:
                    composer-options: '--no-interaction --no-progress --no-dev --no-suggest --no-scripts'

            -   name: Warmup Symfony cache
                run: php bin/console cache:warmup -e prod

            -   name: Install assets
                run: php bin/console assets:install -e prod

            -   name: Configure AWS credentials
                uses: aws-actions/configure-aws-credentials@v2
                with:
                    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
                    aws-region: 'ap-southeast-2'

#            -   name: Delete
#                run: |
#                    sam delete \
#                        --stack-name BowlingCokeMoney \
#                        --region ap-southeast-2 \
#                        --no-prompts

            -   name: Deploy
                run: |
                    sam deploy \
                        --no-confirm-changeset \
                        --stack-name BowlingCokeMoney \
                        --resolve-s3 \
                        --capabilities CAPABILITY_IAM \
                        --region ap-southeast-2